AirplaneASP/Models/Companies/CompaniesModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using AirportService;
using AirportService.DTO;

namespace AirplaneASP.Models.Companies
{
    public class CompaniesModel
    {
        [Display(Name = "Company ID")]
        public Guid ID { get; set; }

        [Display(Name = "Name")]
        public string Name { get; set; }
    }
}

AirplaneASP/Models/Companies/CompanyModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using AirportService;
using AirportService.DTO;

namespace AirplaneASP.Models.Companies
{
    public class CompanyModel
    {
        [Display(Name = "Company ID")]
        public Guid ID { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "Please enter a name")]
        [DataType(DataType.Text, ErrorMessage = "Please enter text")]
        [RegularExpression("([a-zA-Z0-9 .&'-]+)", ErrorMessage = "Invalid character")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Name length must be between 2 and 30")]
        public string Name { get; set; }
    }
}

AirplaneASP/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AirportService;
using AirportService.DTO;
using AirplaneASP.Models.Companies;
using AirplaneASP.Mapping;
using AirplaneASP.Authorization;

namespace AirplaneASP.Controllers
{
    [AuthorizeAccess(Roles = "ADMIN")]
    public class CompaniesController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IMapper<CompanyDTO, CompanyModel> _companyMaper;

        public CompaniesController(ICompanyService companyService,
                                   IMapper<CompanyDTO, CompanyModel> companyModelMaper)
        {
            this._companyService = companyService;
            this._companyMaper = companyModelMaper;
        }

        [HttpGet]
        public ActionResult List()
        {
            List<CompanyDTO> companyDTOList = _companyService.GetAll();
            var companyList = this._companyMaper.Map(companyDTOList);

            return View("List", companyList);
        }

        [HttpGet]
        public ActionResult Remove(Guid id)
        {
            _companyService.Remove(id);

            return RedirectToAction("List");
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(CompanyModel company)
        {
            if (ModelState.IsValid)
            {
                var companyDTO = _companyMaper.MapBack(company);
                _companyService.Add(companyDTO);

                return RedirectToAction("List");
            }
            else return View();
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            ICompanyService companyService = new CompanyService();
            CompanyDTO companyDTO = companyService.GetAll().FirstOrDefault(c => c.ID == id);
            var company = this._companyMaper.Map(companyDTO);

            return View("Edit", company);
        }

        [HttpPost]
        public ActionResult Edit(CompanyModel company)
        {
            if (ModelState.IsValid)
            {
                var companyDTO = _companyMaper.MapBack(company);
                _companyService.Edit(companyDTO);

                return RedirectToAction("List");
            }
            else return View();
        }
    }
}

AirplaneASP/Views/Companies/Add.cshtml
@model AirplaneASP.Models.Companies.CompanyModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CompanyDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List", "Companies")
</div>

AirplaneASP/Views/Companies/Edit.cshtml
@model AirplaneASP.Models.Companies.CompanyModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CompanyDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List", "Companies")
</div>

AirplaneASP/Views/Companies/List.cshtml
@model IEnumerable<AirplaneASP.Models.Companies.CompanyModel>

@{
    ViewBag.Title = "Companies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Companies</h2>

<p>
    @Html.ActionLink("Add", "Add", "Companies")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                <!--
                   @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                -->
                @Html.ActionLink("Remove", "Remove", new { id = item.ID })
            </td>
        </tr>
    }

</table>