AirplaneASP/Models/Flights/FlightModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AirplaneASP.Models.Flights
{
    public class FlightModel
    {
        [Display(Name = "Flight ID")]
        public Guid ID { get; set; }

        [Display(Name = "Company ID")]
        public Guid CompanyID { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "Please enter a name")]
        [DataType(DataType.Text, ErrorMessage = "Please enter text")]
        [RegularExpression("([a-zA-Z0-9 .&'-]+)", ErrorMessage = "Invalid character")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Name length must be between 2 and 50")]
        public string Name { get; set; }

        [Display(Name = "Day of week")]
        [Required(ErrorMessage = "Please enter a day of week")]
        [Range(1, 7, ErrorMessage = "Value must be integer between 1 and 7")]
        public int? DayOfWeek { get; set; }

        [Display(Name = "City departure ID")]
        public Guid CityDepartureID { get; set; }

        [Display(Name = "City arrival ID")]
        public Guid CityArrivalID { get; set; }

        [Display(Name = "Departure time")]
        [Required(ErrorMessage = "Please enter a departure time")]
        [DataType(DataType.Time, ErrorMessage = "Please enter time format")]
        public TimeSpan? DepartureTime { get; set; }

        [Display(Name = "Arrival time")]
        [Required(ErrorMessage = "Please enter an arrival time")]
        [DataType(DataType.Time, ErrorMessage = "Please enter time format")]
        public TimeSpan? ArrivalTime { get; set; }
    }
}

AirplaneASP/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AirportService;
using AirportService.DTO;
using AirplaneASP.Models.Flights;
using AirplaneASP.Models.Companies;
using AirplaneASP.Models.Cities;
using AirplaneASP.Mapping;
using AirplaneASP.Authorization;

namespace AirplaneASP.Controllers
{
    [AuthorizeAccess(Roles = "ADMIN")]
    public class FlightsController : Controller
    {
        private readonly IFlightService _flightService;
        private readonly ICompanyService _companyService;
        private readonly ICityService _cityService;

        private readonly IMapper<FlightDTO, FlightModel> _flightMaper;
        private readonly IMapper<CompanyDTO, CompanyModel> _companyMaper;
        private readonly IMapper<CityDTO, CityModel> _cityMaper;

        public FlightsController(IFlightService flightService,
                                 ICompanyService companyService,
                                 ICityService cityService,
                                 ICountryService countryService,

                                 IMapper<FlightDTO, FlightModel> flightMaper,
                                 IMapper<CompanyDTO, CompanyModel> companyMaper,
                                 IMapper<CityDTO, CityModel> cityMaper)
        {
            this._flightService = flightService;
            this._companyService = companyService;
            this._cityService = cityService;

            this._flightMaper = flightMaper;
            this._companyMaper = companyMaper;
            this._cityMaper = cityMaper;
        }

        [HttpGet]
        public ActionResult List()
        {
            List<FlightDTO> flightDTOList = _flightService.GetAll();
            var flightList = _flightMaper.Map(flightDTOList);          

            return View("List", flightList);
        }

        [HttpGet]
        public ActionResult Remove(Guid id)
        {
            _flightService.Remove(id);

            return RedirectToAction("List");
        }

        public ActionResult Add()
        {
            List<CompanyDTO> companyDTOList = _companyService.GetAll();
            var companyList = _companyMaper.Map(companyDTOList);
            ViewBag.CompanyList = companyList;

            List<CityDTO> cityDTOList = _cityService.GetAll();
            var cityList = _cityMaper.Map(cityDTOList);
            ViewBag.CityList = cityList;

            return View();
        }

        [HttpPost]
        public ActionResult Add(FlightModel flight)
        {
            if (ModelState.IsValid)
            {
                var flightDTO = _flightMaper.MapBack(flight);
                _flightService.Add(flightDTO);

                return RedirectToAction("List");
            }
            else
            {
                List<CompanyDTO> companyDTOList = _companyService.GetAll();
                var companyList = _companyMaper.Map(companyDTOList);
                ViewBag.CompanyList = companyList;

                List<CityDTO> cityDTOList = _cityService.GetAll();
                var cityList = _cityMaper.Map(cityDTOList);
                ViewBag.CityList = cityList;

                return View();
            }
        }


        [HttpGet]
        //[Route("Edit/{flightID}")]
        public ActionResult Edit(Guid id)
        {
            FlightDTO flightDTO = _flightService.GetAll().FirstOrDefault(f => f.ID == id);
            var flight = _flightMaper.Map(flightDTO);

            List<CompanyDTO> companyDTOList = _companyService.GetAll();
            var companyList = _companyMaper.Map(companyDTOList);
            ViewBag.CompanyList = companyList;

            List<CityDTO> cityDTOList = _cityService.GetAll();
            var cityList = _cityMaper.Map(cityDTOList);
            ViewBag.CityList = cityList;

            return View("Edit", flight);
        }

        [HttpPost]
        public ActionResult Edit(FlightModel flight)
        {
            if (ModelState.IsValid)
            {
                var flightDTO = _flightMaper.MapBack(flight);
                _flightService.Edit(flightDTO);

                return RedirectToAction("List");
            }
            else
            {
                List<CompanyDTO> companyDTOList = _companyService.GetAll();
                var companyList = _companyMaper.Map(companyDTOList);
                ViewBag.CompanyList = companyList;

                List<CityDTO> cityDTOList = _cityService.GetAll();
                var cityList = _cityMaper.Map(cityDTOList);
                ViewBag.CityList = cityList;

                return View();
            }
        }
    }
}

AirplaneASP/Views/Flights/Add.cshtml
@model AirplaneASP.Models.Flights.FlightModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>FlightDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CompanyID, new SelectList(ViewBag.CompanyList, "ID", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayOfWeek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DayOfWeek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DayOfWeek, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityDepartureID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CityDepartureID, new SelectList(ViewBag.CityList, "ID", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityDepartureID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityArrivalID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CityArrivalID, new SelectList(ViewBag.CityList, "ID", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityArrivalID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartureTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartureTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartureTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArrivalTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArrivalTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArrivalTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List", "Flights")
</div>

AirplaneASP/Views/Flights/Edit.cshtml
@model AirplaneASP.Models.Flights.FlightModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>FlightDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CompanyID, new SelectList(ViewBag.CompanyList, "ID", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayOfWeek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DayOfWeek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DayOfWeek, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityDepartureID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CityDepartureID, new SelectList(ViewBag.CityList, "ID", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityDepartureID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityArrivalID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CityArrivalID, new SelectList(ViewBag.CityList, "ID", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityArrivalID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartureTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartureTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartureTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArrivalTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArrivalTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArrivalTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List", "Flights")
</div>

AirplaneASP/Views/Flights/Flights.cshtml
@using AirportService.DTO
@model List<FlightDTO>
@{
    ViewBag.Title = "Flights";
}
<h2>@ViewBag.Title.</h2>

@foreach (var flight in @Model)
{
    <div class="row">
        <div class="col-md-3">@flight.Name</div>
        @using (Html.BeginForm())
        {
            @Html.ActionLink("Remove", "Remove", "Flights", new { flightID = @flight.ID }, null)
        }
    </div>


}

AirplaneASP/Views/Flights/List.cshtml
@model IEnumerable<AirplaneASP.Models.Flights.FlightModel>

@{
    ViewBag.Title = "Flights";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Flights</h2>

<p>
    @Html.ActionLink("Add", "Add", "Flights")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CompanyID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DayOfWeek)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CityDepartureID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CityArrivalID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartureTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DayOfWeek)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CityDepartureID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CityArrivalID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArrivalTime)
            </td>
            <td>

                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                <!--
                    @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                 -->
                @Html.ActionLink("Remove", "Remove", new { id = item.ID })
            </td>
        </tr>
    }

</table>