AirplaneASP/Models/Countries/CountryModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AirplaneASP.Models.Countries
{
    public class CountryModel
    {
        [Display(Name = "Country ID")]
        public Guid? ID { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "Please enter a name")]
        [DataType(DataType.Text, ErrorMessage = "Please enter text")]
        [RegularExpression("([a-zA-Z0-9 .&'-]+)", ErrorMessage = "Invalid character")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Name length must be between 2 and 50")]
        public string Name { get; set; }
    }
}

AirplaneASP/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AirportService;
using AirportService.DTO;
using AirplaneASP.Models.Countries;
using AirplaneASP.Mapping;
using AirplaneASP.Authorization;

namespace AirplaneASP.Controllers
{
    [AuthorizeAccess(Roles = "ADMIN")]
    public class CountriesController : Controller
    {
        private readonly ICountryService _countryService;
        private readonly IMapper<CountryDTO, CountryModel> _countryMaper;

        public CountriesController(ICountryService countryService,
                                   IMapper<CountryDTO, CountryModel> countryMaper)
        {
            this._countryService = countryService;
            this._countryMaper = countryMaper;
        }

        [HttpGet]
        public ActionResult List()
        {
            List<CountryDTO> countryDTOList = _countryService.GetAll();
            var countryList = _countryMaper.Map(countryDTOList);

            return View("List", countryList);
        }

        [HttpGet]
        public ActionResult Remove(Guid id)
        {
            _countryService.Remove(id);

            return RedirectToAction("List");
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(CountryModel country)
        {
            if (ModelState.IsValid)
            {
                var countryDTO = _countryMaper.MapBack(country);
                _countryService.Add(countryDTO);

                return RedirectToAction("List");
            }
            else return View();
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            CountryDTO countryDTO = _countryService.GetAll().FirstOrDefault(c => c.ID == id);
            var country = _countryMaper.Map(countryDTO);

            return View("Edit", country);
        }

        [HttpPost]
        public ActionResult Edit(CountryModel country)
        {
            if (ModelState.IsValid)
            {
                var countryDTO = _countryMaper.MapBack(country);
                _countryService.Edit(countryDTO);

                return RedirectToAction("List");
            }
            else return View();
        }
    }
}

AirplaneASP/Views/Countries/Add.cshtml
@model AirplaneASP.Models.Countries.CountryModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CountryDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List", "Countries")
</div>

AirplaneASP/Views/Countries/Countries.cshtml
@using AirportService.DTO
@model List<CountryDTO>
@{
    ViewBag.Title = "Countries";
}
<h2>@ViewBag.Title.</h2>

@foreach (var country in @Model)
{
    <div class="row">
        <div class="col-md-3">@country.Name</div>
        @using (Html.BeginForm())
        {
            @Html.ActionLink("Remove", "Remove", "Countries", new { countryID = @country.ID }, null)
        }
    </div>


}

AirplaneASP/Views/Countries/Edit.cshtml
@model AirplaneASP.Models.Countries.CountryModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CountryDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List", "Countries")
</div>

AirplaneASP/Views/Countries/List.cshtml
@model IEnumerable<AirplaneASP.Models.Countries.CountryModel>

@{
    ViewBag.Title = "Countries";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Countries</h2>

<p>
    @Html.ActionLink("Add", "Add", "Countries")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>

                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                <!--
                   @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                -->
                @Html.ActionLink("Remove", "Remove", new { id = item.ID })
            </td>
        </tr>
    }

</table>