AirplaneASP/Models/Cities/CityModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AirplaneASP.Models.Cities
{
    public class CityModel
    {
        [Display(Name = "City ID")]
        public Guid ID { get; set; }

        [Display(Name = "Country ID")]
        public Guid CountryID { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "Please enter a name")]
        [DataType(DataType.Text, ErrorMessage = "Please enter text")]
        [RegularExpression("([a-zA-Z0-9 .&'-]+)", ErrorMessage = "Invalid character")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Name length must be between 2 and 50")]
        public string Name { get; set; }
    }
}

AirplaneASP/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AirportService;
using AirportService.DTO;
using AirplaneASP.Models.Cities;
using AirplaneASP.Models.Countries;
using AirplaneASP.Mapping;
using AirplaneASP.Authorization;

namespace AirplaneASP.Controllers
{
    [AuthorizeAccess(Roles = "ADMIN")]
    public class CitiesController : Controller
    {
        private readonly ICityService _cityService;
        private readonly ICountryService _countryService;

        private readonly IMapper<CityDTO, CityModel> _cityMaper;
        private readonly IMapper<CountryDTO, CountryModel> _countryMaper;

        public CitiesController(ICityService cityService,
                                ICountryService countryService,

                                IMapper<CityDTO, CityModel> cityMaper,
                                IMapper<CountryDTO, CountryModel> countryMaper)
        {
            this._cityService = cityService;
            this._countryService = countryService;
            this._cityMaper = cityMaper;
            this._countryMaper=countryMaper;
        }

        [HttpGet]
        public ActionResult List()
        {
            List<CityDTO> cityDTOList = _cityService.GetAll();
            var cityList = _cityMaper.Map(cityDTOList);

            return View("List", cityList);
        }

        [HttpGet]
        public ActionResult Remove(Guid id)
        {
            _cityService.Remove(id);

            return RedirectToAction("List");
        }

        public ActionResult Add()
        {
            List<CountryDTO> countryDTOList = _countryService.GetAll();
            var countryList = _countryMaper.Map(countryDTOList);
            ViewBag.CountryList = countryList;
            return View();
        }

        [HttpPost]
        public ActionResult Add(CityModel city)
        {
            if (ModelState.IsValid)
            {
                var cityDTO = _cityMaper.MapBack(city);
                _cityService.Add(cityDTO);

                return RedirectToAction("List");
            }
            else
            {
                List<CountryDTO> countryDTOList = _countryService.GetAll();
                var countryList = _countryMaper.Map(countryDTOList);
                ViewBag.CountryList = countryList;

                return View();
            }
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            CityDTO cityDTO = _cityService.GetAll().FirstOrDefault(c => c.ID == id);
            var city = _cityMaper.Map(cityDTO);

            List<CountryDTO> countryDTOList = _countryService.GetAll();
            var countryList = _countryMaper.Map(countryDTOList);
            ViewBag.CountryList = countryList;

            return View("Edit", city);
        }

        [HttpPost]
        public ActionResult Edit(CityModel city)
        {
            if (ModelState.IsValid)
            {
                var cityDTO = _cityMaper.MapBack(city);
                _cityService.Edit(cityDTO);

                return RedirectToAction("List");
            }
            else
            {
                List<CountryDTO> countryDTOList = _countryService.GetAll();
                var countryList = _countryMaper.Map(countryDTOList);
                ViewBag.CountryList = countryList;

                return View();
            }
        }
    }
}

AirplaneASP/Views/Cities/Add.cshtml
@model AirplaneASP.Models.Cities.CityModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CityDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CountryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CountryID, new SelectList(ViewBag.CountryList, "ID", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CountryID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to list", "List", "Cities")
</div>

AirplaneASP/Views/Cities/Cities.cshtml
@using AirportService.DTO
@model List<CityDTO>
@{
    ViewBag.Title = "Cities";
}
<h2>@ViewBag.Title.</h2>

@foreach (var city in @Model)
{
    <div class="row">
        <div class="col-md-3">@city.Name</div>
        @using (Html.BeginForm())
        {
            @Html.ActionLink("Remove", "Remove", "Cities", new { cityID = @city.ID }, null)
        }
    </div>
}

AirplaneASP/Views/Cities/Edit.cshtml
@model AirplaneASP.Models.Cities.CityModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CityDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CountryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CountryID, new SelectList(ViewBag.CountryList, "ID", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CountryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List", "Cities")
</div>

AirplaneASP/Views/Cities/List.cshtml
@model IEnumerable<AirplaneASP.Models.Cities.CityModel>

@{
    ViewBag.Title = "Cities";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cities</h2>

<p>
    @Html.ActionLink("Add", "Add", "Cities")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CountryID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CountryID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                <!--
                @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                 -->

                @Html.ActionLink("Remove", "Remove", new { id = item.ID })
            </td>
        </tr>
    }

</table>